//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_VisionMaster.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tesst123")]
        public string Test {
            get {
                return ((string)(this["Test"]));
            }
            set {
                this["Test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FolderPathConfig {
            get {
                return ((string)(this["FolderPathConfig"]));
            }
            set {
                this["FolderPathConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Dell\\Desktop\\VisionParket\\VisionParket\\Image\\EnhancementConfig.xml")]
        public string FilePathEnhancement {
            get {
                return ((string)(this["FilePathEnhancement"]));
            }
            set {
                this["FilePathEnhancement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Dell\\Desktop\\VisionParket\\VisionParket\\Image\\SurfaceConfig.xml")]
        public string FilePathSurface {
            get {
                return ((string)(this["FilePathSurface"]));
            }
            set {
                this["FilePathSurface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Dell\\Desktop\\VisionParket\\VisionParket\\Image\\BlodConfig.xml")]
        public string FilePathBoldAnalys {
            get {
                return ((string)(this["FilePathBoldAnalys"]));
            }
            set {
                this["FilePathBoldAnalys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Dell\\Desktop\\VisionParket\\VisionParket\\Image\\\\roi_info.json")]
        public string FileCofigRoiRectang {
            get {
                return ((string)(this["FileCofigRoiRectang"]));
            }
            set {
                this["FileCofigRoiRectang"] = value;
            }
        }
    }
}
